# Generated by Django 4.1.7 on 2023-03-06 23:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(upload_to='static/logos/')),
                ('rotate_duration', models.FloatField(blank=True, null=True)),
                ('modified', models.BooleanField(default=False)),
            ],
        ),
    ]
